name: Publish Package to GitHub Packages
on:
  pull_request:
    branches: [main]
  release:
    type: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permission:
      content: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Publish package
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.COTS_TOKEN }}
